# Production Docker Compose configuration
# Use this file for production deployments with actual AWS services

version: '3.8'

services:
  # In production, we typically use managed services like RDS and ElastiCache
  # This file shows how to configure for production use

  postgres:
    # Use production-grade PostgreSQL image
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-heliumdb}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_prod_data:/var/lib/postgresql/data
    networks:
      - heliolus-prod-network
    # In production, don't expose ports directly
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
        reservations:
          cpus: '1'
          memory: 1G

  redis:
    image: redis:7-alpine
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes
    volumes:
      - redis_prod_data:/data
    networks:
      - heliolus-prod-network
    healthcheck:
      test: ['CMD', 'redis-cli', '--no-auth-warning', '-a', '${REDIS_PASSWORD}', 'ping']
      interval: 30s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Remove pgAdmin and LocalStack from production
  # In production, use cloud-based management tools

volumes:
  postgres_prod_data:
  redis_prod_data:

networks:
  heliolus-prod-network:
    driver: bridge
# Production considerations:
# 1. Use environment variables for all sensitive data
# 2. Implement proper logging and monitoring
# 3. Use managed services (RDS, ElastiCache) when possible
# 4. Implement proper backup strategies
# 5. Use secrets management for sensitive configuration
