name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Update root dependencies
        run: |
          npx npm-check-updates -u
          npm install

      - name: Update frontend dependencies
        run: |
          cd frontend
          npx npm-check-updates -u
          npm install

      - name: Update backend dependencies
        run: |
          cd backend
          npx npm-check-updates -u
          npm install

      - name: Run tests to ensure updates work
        run: |
          npm run lint
          cd frontend && npm run build
          cd ../backend && npm run build

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: automated dependency updates'
          body: |
            This PR updates the project dependencies to their latest versions.

            - ⚡ Updated root dependencies
            - 🎨 Updated frontend dependencies  
            - ⚙️ Updated backend dependencies

            Please review the changes and ensure all tests pass before merging.
          branch: dependency-updates
          delete-branch: true

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm ci
          cd frontend && npm ci
          cd ../backend && npm ci

      - name: Run security audit
        run: |
          npm audit --audit-level=moderate
          cd frontend && npm audit --audit-level=moderate
          cd ../backend && npm audit --audit-level=moderate

      - name: Create security issue if vulnerabilities found
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            const title = 'Security vulnerabilities detected';
            const body = `
            ## Security Audit Failed

            The automated security audit has detected vulnerabilities in the project dependencies.

            Please run the following commands to investigate:

            \`\`\`bash
            npm audit
            cd frontend && npm audit
            cd backend && npm audit
            \`\`\`

            To fix automatically fixable issues:

            \`\`\`bash
            npm audit fix
            cd frontend && npm audit fix
            cd backend && npm audit fix
            \`\`\`
            `;

            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'dependencies']
            });
